name: 2. Deploy

on: 
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8
      
      - run: terraform init
      - run: terraform fmt -recursive -check
      - run: terraform validate
      - run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
    
  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.8

      - name: Dowload Plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  


